### ISSUE TITLE
Discord name not wroking

### ISSUE THREAD

**Issue by ALittlePatate** [Snaacky/snaacky#1]
Hey i can't add you on discord ? Can you update your name plz ?

**Comment by Snaacky** [comment]
The name is accurate. Keep in mind that Discord is case-sensitive. Try again, perhaps?

**Comment by ALittlePatate** [comment]
Well it's working now, i guess i'm just an idiot

**Comment by ALittlePatate** [comment]
can you add me back, i have something for you

**Comment by Snaacky** [comment]
Added.
